# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commiter:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Alias of the commiter'
        # Default value if no value is explicitly provided
        default: 'nirmisha'
        # Input has to be provided for the workflow to run
        required: true
      target_branch:
        description: 'Branch Where to do version bump'
        default: 'BABEL_2_X_DEV'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Auto-Bump-Version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      EXT_BRANCH_URL: https://github.com/shah-nirmit/babelfish_extensions
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      vfile: contrib/babelfishpg_tsql/src/babelfish_version.h
    steps:
        - name: Checkout the repo
          id: checkout-fork
          uses: actions/checkout@v3

        - name: add the remote and setup tracking branch
          id: setup-tr-branch
          run: |
            git remote add upstream ${{ env.EXT_BRANCH_URL }}
            git fetch upstream
            git checkout -b bump-version-${{ github.event.inputs.target_branch}} upstream/${{ github.event.inputs.target_branch}}
            git status
            git branch -vv
        - name: Identify the version to bump
          id: identify-versions
          run: |
            # bump babelfish internal version
            bbf_int_new_version=$(awk -F'[ ."]' '/^#define BABELFISH_INT/ {print $5"."$6"."$7+1"."$8}' ${{ env.vfile }} )
            echo "bbf_int_new_version=$bbf_int_new_version" >> $GITHUB_ENV
            # bump babelfish version
            bbf_new_version=$( awk -F'[ ."]' '/^#define BABELFISH_VER/ {print $4"."$5"."$6+1}' ${{ env.vfile }} )
            echo "bbf_new_version=$bbf_new_version" >> $GITHUB_ENV

        - name: Make commits to bump version and push to remote branch
          run: |
            git config --global user.email "${{ github.event.inputs.commiter }}@amazon.com"
            git config --global user.name "${{ github.event.inputs.commiter }}"
            sed -i -r 's/(.*)(BABELFISH_INTERNAL_VERSION_STR )"(Babelfish )([0-9]+.[0-9]+.)([0-9]+)(.[0-9]+)"/echo "\1\2\\"\3\4$((\5+1))\6\\""/ge' ${{ env.vfile }}
            git add .
            git commit -m "Bump Babelfish Internal Version to ${{ env.bbf_int_new_version }}" -s
            sed -i -r 's/(.*)(BABELFISH_VERSION_STR )"([0-9]+.[0-9]+.)([0-9]+)"/echo "\1\2\\"\3$((\4+1))\\""/ge' ${{ env.vfile }}
            git add .
            git commit -m "Bump Babelfish Version to ${{ env.bbf_new_version }}" -s
            git push -u origin bump-ver-${{ github.event.inputs.target_branch}}

        - name: Raise a PR
          run: |
            gh pr create --title "Bump Babelfish Version to ${{ env.bbf_new_version }}" --repo shah-nirmit/babelfish_extensions --base ${{ github.event.inputs.target_branch }} \
                                                                                       --body "1.Bump Babelfish Version to ${{ env.bbf_new_version }} \n Bump Babelfish Internal Version to ${{ env.bbf_int_new_version }} \n Signed-off-by:  <${{ github.event.inputs.commiter }}@amazon.com>"
